import os
from Crypto.Random import random
from Crypto.Hash import SHA
from flask import Flask, render_template, request, redirect, url_for
from note import Note

dnote = Flask(__name__)
here = dnote.root_path

if not os.path.exists('%s/data/' % here):
    os.makedirs('%s/data' % here)

def send_email(link, recipient):
    """Send the link via email to a recipient.

    Keyword arguments:
    link -- the random url generated by the application
    recipient -- a valid RFC-compliant email address."""

    import email.utils
    import smtplib
    import time
    from email.mime.text import MIMEText
    msg = MIMEText("%s" % link)
    msg['To'] = email.utils.formataddr(('Self Destructing Notes', recipient))
    msg['From'] = email.utils.formataddr((fullname, fromaddr))
    s = smtplib.SMTP('localhost')
    s.sendmail(fromaddr, [recipient], msg.as_string())
    s.quit()

def async(func):
    """Return threaded wrapper decorator.

    Keyword arguments:
    func -- the function this decorator is threading"""

    from threading import Thread
    def wrapper(*args, **kwargs):
        t = Thread(target = func, args = args, kwargs = kwargs)
        t.start()
    return wrapper

@async
def cleanup_unread():
    """Destroy unread notes older than 30 days."""

    while True:
        seek_time = time.time()
        for f in os.listdir('%s/data/' % here):
            file_mtime = os.stat('%s/data/%s' % (here, f))[8]
            if (seek_time - file_mtime) >= 2592000 and 'hashcash.db' not in f:
                secure_remove('%s/data/%s' % (here, f))
        time.sleep(86400) # wait for 1 day

def duress_text():
    """Return 5 random sentences of the Zen of Python."""
    import subprocess
    text = ''
    p = subprocess.Popen(('python','-c','import this'), stdout=subprocess.PIPE,)
    s = [x for x in p.communicate()[0].splitlines() if x != '']
    for i in range(5):
        text = text + random.choice(s) + ' '
    return text

def verify_hashcash(token):
    """Return True or False based on the Hashcash token

    Valid Hashcash tokens must start with '0000' in the SHA hexdigest string.
    If not, then return False to redirect the user to an error page. If the
    token is valid, but has already been spent, then also return False to
    redirect the user to an error page. Otherwise, if the token is valid and
    has not been spent, append it to the hashcash.db file.

    Keyword arguments:
    token -- a proposed Hashcash token to validate."""

    digest = SHA.new(token)
    with open('%s/data/hashcash.db' % here, 'a+') as f:
        if digest.hexdigest()[:4] == '0000' and token not in f.read():
            f.write(token+'\n')
            return True
        else:
            return False

@dnote.route('/', methods = ['GET'])
def index():
    """Return the index.html for the main application."""
    error = request.args.get('error',None)
    note = Note()
    return render_template('index.html', random = note.url, error = error)

@dnote.route('/security/', methods = ['GET'])
def security():
    """Return the index.html for the security page."""
    return render_template('security.html')

@dnote.route('/faq/', methods = ['GET'])
def faq():
    """Return the index.html for the faq page."""
    return render_template('faq.html')

@dnote.route('/about/', methods = ['GET'])
def about():
    """Return the index.html for the about page."""
    return render_template('about.html')

@dnote.route('/post', methods = ['POST'])
def show_post():
    """Return the random URL after posting the plaintext."""
    new_url = request.form["new_url"]
    note = Note(new_url)
    note.plaintext = request.form['paste']

    passphrase = request.form.get('pass',False)
    duress = request.form.get('duress',False)
    token = request.form['hashcash']

    if not verify_hashcash(token):
        return redirect(url_for('index',error='hashcash'))
    if duress and not passphrase:
        return redirect(url_for('index',error='duress'))

    if passphrase:
        note.set_passphrase(passphrase)
        note.encrypt()
        if duress:
            note.duress_key()
            return render_template('post.html', random = note.url, passphrase = note.passphrase, duress = note.dkey)
        return render_template('post.html', random = note.url, passphrase = note.passphrase)
    else:
        note.encrypt()
        return render_template('post.html', random = note.url)

@dnote.route('/<random_url>', methods = ['POST', 'GET'])
def fetch_url(random_url):
    """Return the decrypted note. Begin short destruction timer.

    Keyword arguments:
    random_url -- Random URL representing the encrypted note."""

    note = Note(random_url)

    if not os.path.exists(note.path()):
        return render_template('404.html'), 404
    elif os.path.exists(note.path('key')) and request.method != 'POST':
        return render_template('key.html', random = note.url)
    elif os.path.exists(note.path('key')) and request.method == 'POST':
        passphrase = request.form['pass']
        note.set_passphrase(passphrase)
        if passphrase == note.dkey:
            note.secure_remove()
            return render_template('note.html', text = duress_text())
        else:
            if note.decrypt():
                note.secure_remove()
                return render_template('note.html', text = note.plaintext)
            else:
                return render_template('keyerror.html', random = note.url)
    else:
        if note.decrypt():
            note.secure_remove()
            return render_template('note.html', text = note.plaintext)
        else:
            return render_template('404.html'), 404

if __name__ == '__main__':
    dnote.debug = True
    #cleanup_unread()
    dnote.run()
